apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: octopus
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: pro
          ports:
            - containerPort: 3344
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Never
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: octopus
  labels:
    app: gateway
  annotations:
    kubesphere.io/alias-name: gateway
    kubesphere.io/description: 路由网关
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3344
      targetPort: 3344
      #需要修改
      nodePort: 30010
  selector:
    app: gateway
  type: NodePort
  sessionAffinity: None
