server:
  port: 9001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: nacos-provider

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.200:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

  devtools:
    restart:
      enabled: true #是否支持热部署
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.200:8848


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zgm.cloud.entity  #所有entity别名所在包

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:9999/user/current/get
#      id: account-service


management:
  endpoints:
    web:
      exposure:
        include: "*"
