apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-party
  namespace: octopus
  labels:
    app: third-party
spec:
  replicas: 1
  selector:
    matchLabels:
      app: third-party
  template:
    metadata:
      labels:
        app: third-party
    spec:
      containers:
        - name: third-party
          #jenkinsfile读取
          image: third-party:latest
          ports:
            - containerPort: 9003
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Never
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: third-party
  namespace: octopus
  labels:
    app: third
  annotations:
    kubesphere.io/alias-name: third-party
    kubesphere.io/description: third-party
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9003
      targetPort: 9003
      #需要修改
      nodePort: 30014
  selector:
    app: third-party
  type: NodePort
  sessionAffinity: None
