server:
  port: 9999

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/cloud?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

  devtools:
    restart:
      enabled: true #是否支持热部署
  cloud:
    nacos:
      discovery:
        server-addr: nacos

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zgm.cloud.entity  #所有entity别名所在包


management:
  endpoints:
    web:
      exposure:
        include: "*"
#security:
#  oauth2:
#    client:
#      client-id: zgm
#      client-secret: zgmsecret

