apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: octopus
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          #jenkinsfile读取
          image: auth:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: pro
          ports:
            - containerPort: 9999
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Never
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: octopus
  labels:
    app: auth
  annotations:
    kubesphere.io/alias-name: auth
    kubesphere.io/description: auth
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9999
      targetPort: 9999
      #需要修改
      nodePort: 30011
  selector:
    app: auth
  type: NodePort
  sessionAffinity: None
